from turtle import *

tree_coef = 100

def triangle(dir, a):
    color("green")
    if dir == 'dn':
        begin_fill()
        fd(a)
        lt(60)
        bk(a)
        lt(60)
        fd(a)
        rt(120)
        rt(90)
        lt(90)
        end_fill()
    elif dir == 'up':
        begin_fill()
        fd(a)
        rt(60)
        bk(a)
        rt(60)
        fd(a)
        lt(120)
        end_fill()
    elif dir == 'rt':
        begin_fill()
        rt(30)
        fd(a)
        lt(60)
        bk(a)
        lt(60)
        fd(a)
        rt(90)
        end_fill()
    elif dir == 'lt':
        begin_fill()
        lt(30)
        bk(a)
        rt(60)
        fd(a)
        rt(60)
        bk(a)
        lt(90)
        end_fill()

def sgoto(x, y):
    up()
    width(2)
    goto(x, y)

def rectangle(a, b):
    color("brown")
    begin_fill()
    fd(a)
    rt(90)
    fd(b)
    rt(90)
    fd(a)
    rt(90)
    fd(b)
    rt(90)
    end_fill()

# first tree
rectangle(25, 100)
sgoto(25, 0)
triangle('rt', 45)
sgoto(25, -45)
triangle('rt', 45)
sgoto(0, 0)
triangle('lt', 45)
sgoto(0, -45)
triangle('lt', 45)
sgoto(-10, 0)
triangle('up', 45)

# second tree
sgoto(25 + 75, 0)
rectangle(25, 100)
sgoto(25 + tree_coef, 0)
triangle('rt', 45)
sgoto(25 + tree_coef, -45)
triangle('rt', 45)
sgoto(0 + tree_coef, 0)
triangle('lt', 45)
sgoto(0 + tree_coef, -45)
triangle('lt', 45)
sgoto(-10 + tree_coef, 0)
triangle('up', 45)

# thrid tree
sgoto(25 - tree_coef - 25, 0)
rectangle(25, 100)
sgoto(25 - tree_coef, 0)
triangle('rt', 45)
sgoto(25 - tree_coef, -45)
triangle('rt', 45)
sgoto(0 - tree_coef, 0)
triangle('lt', 45)
sgoto(0 - tree_coef, -45)
triangle('lt', 45)
sgoto(-10 - tree_coef, 0)
triangle('up', 45)

